# Generated by Django 5.1.7 on 2025-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
