# Generated by Django 5.1.7 on 2025-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
