# Generated by Django 5.1.7 on 2025-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_brands_brand'),
        ('categories', '0002_rename_categories_category'),
        ('inflow', '0001_initial'),
        ('outflow', '0002_outflow_cost_price'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
